### ISSUE TITLE
How to set sampling frequencies <100k?

### ISSUE THREAD

**Issue by Modiug** [analogdevicesinc/gr-m2k#28]
When I set a "Sampling frequency" of 10k, I get this:
"RuntimeError: ERR: Runtime - Device: Cannot set the number of kernel buffers"

I tried different "Buffer sizes" and "Kernel buffers", but to no avail.
I was able to set "Sampling freqency" to 100k and "Oversampling ratio" to 8, which gives an effective sample rate of 12.5k. But using an "Oversampling ratio" of 10 again leads to the above error message.

Could somebody point out the limits and relationsships between "Sampling frequency", "Buffer size" and "Kernel buffers"?

**Comment by Modiug** [comment]
The libm2k team came back to me and couldn't reproduce it when using Python code directly.

I still have the issue with radioconda-2023.11.06-Windows-x86_64.

To reproduce:
1. Open "GNU Radio Companion"
2. Pull an "M2k Analog In Source" into the flow graph
3. Set "Sampling frequency" to "samp_rate"
4. Set "samp_rate" variable to 100k
5. Add two QT GUI Time Sinks and connect them to the outputs of "M2k Analog In Source"
6. Run flow graph => should work!
7. Set "samp_rate" to 10k
8. Run flow graph again

where I get:
```
Generating: 'C:\\Users\\...\\Documents\\adalm2000_samplerate.py'

Executing: C:\Users\...\AppData\Local\radioconda\python.exe -u C:\Users\...\Documents\adalm2000_samplerate.py

Traceback (most recent call last):
  File "C:\Users\...\Documents\adalm2000_samplerate.py", line 221, in <module>
    main()
  File "C:\Users\...\Documents\adalm2000_samplerate.py", line 199, in main
    tb = top_block_cls()
         ^^^^^^^^^^^^^^^
  File "C:\Users\...\Documents\adalm2000_samplerate.py", line 165, in __init__
    self.m2k_analog_in_source_0 = m2k.analog_in_source('ip:192.168.2.1', 32768, [True, True], [0, 0], samp_rate, 1, 4, True, True, [0, 0], [0, 0], 0, 0, [1, 1], True)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ERR: Runtime - Device: Cannot set the number of kernel buffers

>>> Done (return code 1)
```

**Comment by AlexandraTrifan** [comment]
The latest libm2k release v0.8.0 was published. https://github.com/analogdevicesinc/libm2k/releases/tag/v0.8.0
This release should fix the issue you mentioned. 
Could you update to the latest version and verify if this is still a problem?

Thank you!
-Alexandra
